### PR TITLE
Fix watch

### PR DESCRIPTION
**Pull request by jon-stevens**
Small fix to the `start:dev` script so that it watches scss and js files

### CODE REVIEW

**Review by jpw — APPROVED** [review]
ty!

**Review by benjclark — APPROVED** [review]
Oh nice one. This was a pain and we keep forgetting to fix it

**Comment by tulipdexter** [comment]
I know this is merged, but isn't this what the `dev` script already does?
https://github.com/springernature/frontend-express-demo/pull/8/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12

**Comment by tulipdexter** [comment]
`"dev": "npm-run-all --parallel start:dev \"build:* -- --watch\""`
Runs the `start:dev` as well as all `build:` tasks, passing them the `--watch` parameter

**Pull request merged**
